### ISSUE TITLE
shape rotation not working anymore

### ISSUE THREAD

**Issue by jalbanesi** [snowkit/differ#13]
If I set shape.rotation = 45, the shape rotates each time I update the value instead of keeping it at 45º

**Comment by ubald** [comment]
Probably related issue here. With the 1.1.0 haxelib version if I change the position of a rotated shape it'll rotate by the rotation amount on every translation.

**Comment by SavedByZero** [comment]
I'm seeing it also.  I use this for collision detection in Flambe, and it works fine until you rotate the sprite; rotating the shape with the sprite doesn't rotate the collision-sensitive area.

**Comment by underscorediscovery** [comment]
did you see this was merged already in master? https://github.com/underscorediscovery/hxcollision/pull/14

Also note that we are doing a new haxelib release in the next week or so, with lots of fixes/cleanup/features.

**Comment by SavedByZero** [comment]
Yes I have the haxelib version which I downloaded a week or so ago, that could be why I didn't have these changes.   But I just implemented the changes from that merge and it still isn't working right.  The collision sensitive area is still to the upper right corner / right side of the rotated targets, to the point where I'll destroy the target to the right of the target I hit sometimes.

**Comment by SavedByZero** [comment]
FYI, I was able to use a workaround.  I set the shape rotation to be the same as the sprite rotation, but before I translated the shape to move where the sprite moved, I had to set the shape rotation to 0.  Otherwise if the shape rotation was > 0, it would keep rotating every time I translated it to where the sprite was.
